
# definitions for the axes
left, width = 0.1, 0.65
bottom, height = 0.1, 0.65
bottom_h = left_h = left+width+0.02
rect_scatter = [left, bottom, width, height]
rect_histx = [left, bottom_h, width, 0.2]
rect_histy = [left_h, bottom, 0.2, height]
# start with a rectangular Figure
plt.figure(1, figsize=(8,8))
axScatter = plt.axes(rect_scatter)
axHistx = plt.axes(rect_histx)
axHisty = plt.axes(rect_histy)
halo_v, halo_feh = np.loadtxt('1344124484.054352.resu', usecols=(15, 19))
halo_v = np.loadtxt('1344124484.054352.resu', usecols=(15, 19))
halo
halo_v
halo_feh = halo_v[:,1]
halo_v = halo_v[:, 0]
halo_v
axScatter.scatter(halo_v, halo_feh, facecolor='k')
xHist = axHistx.hist(halo_v)
yHist = axHisty.hist(halo_feh, orientation='horizontal')
plt.draw()
axScatter.set_xlim(-400, 400)
axScatter.set_xlim(-350, 350)
axHistx.set_xlim(-350, 350)
xHist.set_facecolor('k')
xHist
axHistx.hist(x, facecolor='#666666')
axHistx.hist(halo_v, facecolor='#666666')
axHisty.hist(halo_feh, facecolor='#666666')
plt.draw()
axHistx.clear()
axHisty.clear()
axHistx.hist(halo_v, facecolor='none')
axHisty.hist(halo_feh, facecolor='none', orientation='horizontal')
plt.draw()
axHistx.set_xlabel('')
axHisty.set_ylabel('')
axHistx.get_xticks()
axHistx.set_xticklabels(['']*7)
axHisty.get_yticks()
axHisty.set_yticklabels(['']*9)
plt.draw()
axScatter.set_xlabel('$V_{helio}$ (km/s)')
axScatter.set_ylabel('[Fe/H]')
plt.draw()
star = axScatter.scatter([307], [-1.44], facecolor='k', marker='*', size=50)
star = axScatter.scatter([307], [-1.44], facecolor='k', marker='*', s=50)
plt.draw()
star.set_visible(False)
star = axScatter.scatter([307], [-1.44], facecolor='k', marker='*', s=100)
plt.draw()
star.set_visible(False)
star = axScatter.scatter([307], [-1.44], facecolor='k', marker='*', s=200)
plt.draw()
axScatter.clear()
axScatter.scatter(halo_v, halo_feh, facecolor='none')
star = axScatter.scatter([307], [-1.44], facecolor='k', marker='*', s=200)
plt.draw()
axScatter.set_xlim(-350, 350)
plt.draw()
axHistx.set_xlim(-350, 350)
plt.draw()
axScatter.set_xlabel('$V_{helio}$ (km/s)')
axScatter.set_ylabel('[Fe/H]')
plt.draw()
plt.savefig('besancon.pdf')
axHistx.set_ylabel('N')
axHisty.set_xlabel('N')
plt.draw()
plt.savefig('besancon.pdf')
plt.savefig('besancon.eps')
cmds = "\n".join(In)
out = open('plot-besancon.py', 'w')
out.write(cmds)
out.close()
get_ipython().system(u'vi plot-besancon.py')
get_ipython().system(u'vi plot-besancon.py')
plt.savefig('besancon.eps')
axHistx.set_yticklabels(axHistx.get_yticklabels, font_size=7)
axHistx.set_yticklabels(axHistx.get_yticklabels(), font_size=7)
axHistx.set_yticklabels(axHistx.get_yticklabels(), size=7)
plt.draw()
axHistx.set_yticklabels(map(str, axHistx.get_yticks()), size=7)
plt.draw()
axHistx.set_yticks([0, 300, 600])
plt.draw()
axHist.set_yticklabels(['0', '300', '600'])
axHistx.set_yticklabels(['0', '300', '600'])
plt.draw()
axHistx.set_yticklabels(['0', '300', '600'], size=11)
plt.draw()
axHistx.set_yticklabels(['0', '300', '600'], size=12)
plt.draw()
axHisty.set_xticks([0, 300, 600])
axHisty.set_xticklabels(['0', '300', '600'])
plt.draw()
axHisty.set_xticklabels(['0', '250', '500'])
axHisty.set_xticks([0, 250, 500])
axHisty.set_xlim(0, 750)
plt.draw()
axHistx.set_ylim(0, 750)
plt.draw()
axHistx.set_ylim(0, 800)
plt.draw()
axHisty.set_xticklabels(['0', '300', '600'])
axHisty.set_xticks([0, 300, 600])
plt.draw()
plt.savefig('besancon.eps')
plt.savefig('besancon.pdf')
get_ipython().system(u'open .')
